### ISSUE TITLE
accompagnement et ce qu'on boit avec ça

### ISSUE THREAD

**Issue by BertrandLenclos** [BertrandLenclos/recettesdefamille-livre#2]
Au début de la liste des astuces, intégrer "En accompagnement" ajouter un espace, 2 points, un espace puis texte de la section sans la majuscule.
À la fin de la liste des astuces, intégrer "Ce qu'on boit avec ça" ajouter un espace, 2 points, un espace puis texte de la section sans la majuscule.

**Comment by LeonLenclos** [comment]
réglé
