### ISSUE TITLE
Décalage du CSS inexorable...

### ISSUE THREAD

**Issue by BertrandLenclos** [BertrandLenclos/recettesdefamille-livre#40]
Après avoir perdu ma mise en page d'un instant à l'autre, et réglé le problème en modifiant   
    margin-top: 19mm; 
J'ai été tranquille une semaine. Et le problème est réapparu ce dimanche 13/11/2022 à 21h30.
Cette fois ci je l'ai réglé avec : 
    margin-bottom: 9mm;
Y pas de raison !
J'espère être tranquille pendant 1 semaine.
On dirait un arrondi qui incrémente une valeur petit à petit...

**Comment by LeonLenclos** [comment]
choquant.
