### ISSUE TITLE
liste ingrédients

### ISSUE THREAD

**Issue by BertrandLenclos** [BertrandLenclos/recettesdefamille-livre#5]
Gestion des listes d'ingrédients qui excède la page. Ex : bière à papa

**Comment by LeonLenclos** [comment]
ça va etre compliqué, j'ai croisé d'autres gens qui avaient ce problème sans solution

**Comment by BertrandLenclos** [comment]
Il n'y a que pour la Bière à papa que ça pose problème, je modifie la mise en page sur le site et je close
