### ISSUE TITLE
intégration Photos

### ISSUE THREAD

**Issue by BertrandLenclos** [BertrandLenclos/recettesdefamille-livre#6]
intégrer une balise pour les photos du livre dans le wiki.
Plusieurs possibilités:
- une photo portrait pleine page ou 2 photos paysages superposées à gauche, avant la recette.
- une photo portrait pleine page ou 2 photos paysages superposées à droite, après  la recette.
- une photo en bas d'une page dont la recette est courte.
- une photo double page. 

- A voir comment intégrer tout ça au wiki.

**Comment by LeonLenclos** [comment]
Créer un modèle BookImg qui s'utilise comme ça

`{{BookImg|img1="lien/de/l/image/1"|img2="lien/de/l/image/2"|pos=before}}`

- `img1` le lien de l'image
- `img2` idem mais facultatif
- `pos` peut avoir les valeurs de : `before`, `after` ou `inside`

**Comment by LeonLenclos** [comment]
Ok : http://recettesdefamille.wiki/index.php?title=Mod%C3%A8le:ImageDuLivre
