### ISSUE TITLE
traitement des pages spéciales hors couverture

### ISSUE THREAD

**Issue by BertrandLenclos** [BertrandLenclos/recettesdefamille-livre#7]
En tête :
- Page de garde
- Avant propos
- Auteur
- Sommaire
En fin :
- Index par catégorie
- Bibliographie 
- Lexique
- Page légale

**Comment by LeonLenclos** [comment]
Créer une page BookIndex qui contient une liste de page et de catégories

Le script inclue dans l'ordre chaque page et chaque page listée de chaque catégorie listée

**Comment by LeonLenclos** [comment]
Ok c'est là http://recettesdefamille.wiki/index.php?title=IndexDuLivre
